# Generated by Django 5.2.5 on 2025-08-14 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avg_hours_week',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='main_platform',
            field=models.CharField(blank=True, null=True),
        ),
    ]
