# Generated by Django 5.2.5 on 2025-08-14 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_avg_hours_week_user_main_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='main_platform',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
